# Generated by Django 3.0.8 on 2020-08-27 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200824_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch',
            field=models.ManyToManyField(related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
