# Generated by Django 3.0.8 on 2020-08-27 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
