# Generated by Django 3.0.8 on 2020-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200827_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(default='https://www.thebluediamondgallery.com/wooden-tile/images/auction.jpg', max_length=350),
        ),
    ]
