# Generated by Django 3.0.8 on 2020-08-28 21:57

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200828_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.CharField(default='https://www.thebluediamondgallery.com/wooden-tile/images/auction.jpg', max_length=350),
        ),
    ]
